apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus
  namespace: hammad-argocd  # Replace with your Argo CD namespace
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://192.168.49.2:8443  # Replace with your actual cluster URL
      # Add more clusters as needed

  template:
    metadata:
      name: 'prometheus-{{cluster}}'
      labels:
        app: prometheus
        scope: monitoring
    spec:
      project: devops
      source:
        repoURL: https://github.com/mhammadsaani/kube-prom-stack
        targetRevision: HEAD
        path: charts/kube-prometheus-stack
        helm:
          valueFiles: 
            - "../values-common.yaml"
            - "../values-{{cluster}}.yaml"
      destination:
        server: '{{url}}'
        namespace: hammad-monitoring  # This namespace will be created if it does not exist
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 2
          backoff:
            duration: "5s"
            factor: 2
            maxDuration: "3m0s"
