prometheus:
    prometheusSpec:
      serviceMonitorSelector:
        matchLabels:
          app: prometheus
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
      retention: 10d
      replicas: 1
  
  grafana:
    adminPassword: "admin"
    sidecar:
      dashboards:
        enabled: true
  