apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: test
        url: https://kubernetes.default.svc

  template:
    metadata:
      name: 'prometheus-{{cluster}}'
      labels:
        app: prometheus
        scope: monitoring
    spec:
      project: default
      source:
        repoURL: https://github.com/mhammadsaani/kube-prom-stack
        targetRevision: HEAD
        path: charts/kube-prometheus-stack
        helm:
          valueFiles:
            - "./values-common.yaml"
            - "./values-{{cluster}}.yaml"
      destination:
        server: '{{url}}'
        namespace: hammad-monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 2
          backoff:
            duration: "5s"
            factor: 2
            maxDuration: "3m0s"
