apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-prom-stack
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: cluster1
        url: https://kubernetes.default.svc
      - cluster: cluster2
        url: https://09d151c5-3c8a-4205-a52a-c64b9ca20d60.us-southeast-1-gw.linodelke.net:443


  template:
    metadata:
      name: 'kube-prom-stack-{{cluster}}'
      labels:
        app: prometheus
        scope: monitoring
    spec:
      project: default
      source:
        repoURL: https://github.com/mhammadsaani/kube-prom-stack
        targetRevision: HEAD
        path: charts/kube-prometheus-stack
        helm:
          valueFiles:
            - "values-common.yaml"
            - "values-{{cluster}}.yaml"
      destination:
        server: '{{url}}'
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
